spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/insurance #jdbc:mysql://mjutask-db.c5tjoxciejrk.ap-northeast-2.rds.amazonaws.com:3306/webpro
        username: root
        password: wodnd0131
